### ISSUE TITLE
wiringPiSetup*: You must only call this once per program run. This is a fatal error. Please fix your code.

### ISSUE THREAD

**Issue by shaktiphartiyal** [Pi4J/pi4j-v1#278]
Whenver LCD is used along with any other GPIO instance the error **wiringPiSetup*: You must only call this once per program run. This is a fatal error. Please fix your code.** is thrown and the program exits.
Even the LCD Example Program doesn't run.

**Comment by BigDrakar** [comment]
I have solved this issue commenting line 51 of _com.pi4j.component.lcd.impl.**GpioLcdDisplay**_

**Comment by shaktiphartiyal** [comment]
Yes this seems to work , after removing the line 51 I included the code of the file in my own package named Core and rather than using GpioLcdDisplay simply use Core.LCDLib and the code runs smoothy.
Thank you Tutankhamon for the fix.
Below is the new updated code that we need to use.

```
package Core;
import com.pi4j.component.lcd.LCD;
import com.pi4j.component.lcd.LCDBase;
import com.pi4j.io.gpio.Pin;
import com.pi4j.wiringpi.Lcd;

public class LCDLib extends LCDBase implements LCD
{
    protected int rows;
    protected int columns;
    private int lcdHandle;
    public LCDLib(int rows, int columns, Pin rsPin, Pin strobePin, Pin... dataPins) {
        this.rows = rows;
        this.columns = columns;
        int bits[] = { 0,0,0,0,0,0,0,0 };
        // set wiringPi interface for internal use
        // we will use the WiringPi pin number scheme with the wiringPi library
        //com.pi4j.wiringpi.Gpio.wiringPiSetup();--------THIS IS THE FIX (REASON FOR INCLUSION)

        // seed bit pin address array
        for(int index = 0; index < 8; index++) {
            if(index < dataPins.length)
                bits[index] = dataPins[index].getAddress();
        }

        // initialize LCD
        lcdHandle = Lcd.lcdInit(rows,
                                columns,
                                dataPins.length,
                                rsPin.getAddress(),
                                strobePin.getAddress(),
                                bits[0], bits[1], bits[2], bits[3], bits[4], bits[5], bits[6], bits[7]);

        // verify LCD initialization
        if (lcdHandle == -1)
            throw new RuntimeException("Invalid LCD handle returned from wiringPi: " + lcdHandle);
    }

    @Override
    public int getRowCount() {
        return rows;
    }

    @Override
    public int getColumnCount() {
        return columns;
    }

    @Override
    public void clear() {
        Lcd.lcdClear(lcdHandle);
    }

    @Override
    public void setCursorHome() {
        Lcd.lcdHome(lcdHandle);
    }

    @Override
    public void setCursorPosition(int row, int column) {
        validateCoordinates(row, column);
        Lcd.lcdPosition(lcdHandle, column, row);
    }

    @Override
    public void write(byte data) {
        Lcd.lcdPutchar(lcdHandle, data);
    }

    @Override
    public void write(String data) {
        Lcd.lcdPuts(lcdHandle, data);
    }
}
```

**Comment by savageautomate** [comment]
Re-opening because this still needs to get fixed in the project.

**Comment by Swinkid** [comment]
Any update on this?

**Comment by duygur** [comment]
Any update?

**Comment by savageautomate** [comment]
New 1.2-SNAPSHOT build published with this fix.

**Comment by vdegrandpre** [comment]
Hi savageautomate. Seems not fixed when it is wanted to set BROADCOM_PIN_NUMBERING AND uses LCD. I got the same message `wiringPiSetup*: You must only call this once per program run. This is a fatal error. Please fix your code.`

Snippet :

`try {
			GpioFactory.setDefaultProvider( new RaspiGpioProvider(RaspiPinNumberingScheme.BROADCOM_PIN_NUMBERING) );
			lcd = new GpioLcdDisplay(
					LCD_ROWS,
					LCD_COLS,
					RaspiBcmPin.GPIO_04,
					RaspiBcmPin.GPIO_13,
					RaspiBcmPin.GPIO_05,
					RaspiBcmPin.GPIO_06,
					RaspiBcmPin.GPIO_16,
					RaspiBcmPin.GPIO_12
			);
			PalLog.v(TAG, "GpioLcdDisplay created");
		} catch(Exception e){
			PalLog.v(TAG, "Failed to create GpioLcdDisplay");
			lcd = null;
		}
`

What do you suggest ?
